### ISSUE TITLE
I am trying to configure Swagger with my Play-2.5 project,  not works.

### ISSUE THREAD

**Issue by skanel** [jamesward/play-rest-security#12]
I am trying to configure Swagger with my Play-2.5 project. 

I followed this tutorial and it worked, but only for the older version of Play and not working with Play-2.5. As the project has migrated into Play-2.5, we had to remove the swagger configuration.

Firstly, the issue seemed to be with static controller vs non static controller in Play-2.5, but I ended up with proving myself wrong.
I am facing this error  

          type ApiHelpController is not a member of package controllers 
          GET         /api-docs                controllers.ApiHelpController.getResources

If possible , please guide.

**Comment by jamesward** [comment]
I had issues trying to get Swagger working on with Play 2.5 on this project so I removed it.  Maybe you can get help here: https://github.com/swagger-api/swagger-play
